version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"

  - package-ecosystem: nuget
    directory: "/"
    target-branch: dev
    schedule:
      interval: daily