name: WPF Release

on:
  workflow_dispatch:
  push:
    branches: [main]  
    tags: 
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest 

    env:
      Solution_Name: Turnbind.sln
      Wpf_Project_Directory: Turnbind/
      Wpf_Project_Path: Turnbind/Turnbind.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name:  Restore
      run: msbuild $env:Wpf_Project_Path /t:Restore /p:Configuration=Release

    - name: Build app
      run: msbuild $env:Wpf_Project_Path /p:Configuration=Release

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ./.github/actions/gh-release
      with:
        project-dir: $env:Wpf_Project_Directory
      secrets:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
