name: WPF Release

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest 

    env:
      Solution_Name: Turnbind.sln
      Wpf_Project_Directory: Turnbind/
      Wpf_Project_Path: Turnbind/Turnbind.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create the app package
      run: msbuild $env:Wpf_Project_Path /p:Configuration=Release
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        path: './${{ env.Wpf_Project_Directory }}/bin/Release/'
        filename: release.zip
        
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
